title: "TheIndieGameLab"
email: pingfangwe222@gmail.com
timezone: UTC
baseurl: "/TheIndieGameLab.github.io"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Cat
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Cat
    display_name: Cat
    avatar: 'assets/images/cat.jpg'
    email: pingfangwe222@gmail.com
    web: https://pingfangw.github.io/TheIndieGameLab.github.io/
    twitter: https://pingfangw.github.io/TheIndieGameLab.github.io/
    description: "独立游戏开发者，整理开发过程中学习的资料."
  # john:
  #   name: John
  #   display_name: John
  #   avatar: 'assets/images/john.png'
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net/category/jekyll-themes/
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://pingfangw.github.io/TheIndieGameLab.github.io/
  facebook: https://pingfangw.github.io/TheIndieGameLab.github.io/
  twitter: https://pingfangw.github.io/TheIndieGameLab.github.io/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives